AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**'
    - 'config/initializers/*'
    - 'db/schema.rb'
    - 'db/migrate/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  CountAsOne: ['hash', 'array', 'heredoc']
  Exclude:
    - 'spec/**/*.rb'
