version: '3.7'
networks:
  furball-roulette:
    external: false
    driver: bridge
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - furball-roulette
    expose:
      - "5432"
  rails:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app
    depends_on:
      - db
    networks:
      - furball-roulette

volumes:
  postgres:
