default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_URL", 'db') %>
  database: <%= ENV.fetch("DATABASE_NAME", 'furball-roulette') %>
  username: <%= ENV.fetch("DATABASE_USERNAME", 'postgres' ) %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", 'postgres' ) %>
  port: <%= ENV.fetch("DATABASE_PORT", '5432' ) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5 )  %>

development:
  <<: *default
  database: furball_roulette_development

test:
  <<: *default
  database: furball_roulette_test

